### ISSUE TITLE
ImageDefinition or ContainerImage?

### ISSUE THREAD

**Issue by stain** [openbases/extract-dockerfile#6]
The [ImageDefinition example](https://github.com/openbases/extract-dockerfile/blob/master/ImageDefinition/recipe.yml) uses a type `ImageDefinition` which seems to be a rehash of [ContainerImage](https://openschemas.github.io/specifications/ContainerImage/)

Should this be `ImageDefinition` or `ContainerImage`? The use of _definition_ sounds odd given that it is about the container image - not it's definition/recipe! (Any schema.org metadata necessarily is a description).  Also `Image` can be a photo, which would be misleading here.

**Comment by vsoch** [comment]
Very good question! They are in fact essentially the same - the names / specifications went through a lot of [discussion](https://groups.google.com/a/opencontainers.org/forum/#!searchin/dev/ImageDefinition%7Csort:date/dev/vEupyIGtvJs/RwTwUcCsAwAJ) on the opencontainers list - and largely many had opinions and ImageDefinition was suggested. My preference was for ContainerImage (hence why it's still [here](https://openschemas.github.io/specifications/)) and for the exact reasons you mentioned, but ImageDefinition remained as an artifact of the previous discussion. I'll rename the example to match what (at least we agree) is a better direction.

**Comment by vsoch** [comment]
And sidenote - asking people for suggestions on a list is a terrible way to get consensus... something something too many cooks. :)

**Comment by vsoch** [comment]
okay, just updated #5
